name: DroolChat
author: akselm
version: 1.0
main: com.thestratagemmc.droolchat.DroolChat
commands:
  reply:
    aliases: [r]
  message:
    aliases: [msg,m,whisper,tell,t]
  channel:
    aliases: [ch]
  playerafk:
    aliases: [pafk]